spring:
##  mvc:
##    static-path-pattern: /res/**          //设置指定路径用于拦截，会导致8080默认端口的默认欢迎页无法显示
  web:
     resources:
       add-mappings: true       #  false 禁用所有静态资源规则, 默认为true
       cache:
         #period: 11000     #缓存策略    让浏览器缓存静态资源一段时间，该时间内不必重复请求
#      static-locations:          #先找Mapping动态路由，再找静态资源指定路径。   访问路由为  8080/res/xxxx.png （动态返回，静态去指定路径找）
#        classpath: /static/
  mvc:
    hiddenmethod:       #hiddenmethod一种Filter拦截器HiddenHTTPMethod       所以必须要用POST
      filter:
        enabled: true    #默认为false, true会开启hiddenmethod模式，使得DELET和PUT请求可以以隐藏方式通过POST进行提交

    contentnegotiation:
      favor-parameter: true    #开启参数方式的内容协商（总体上存在两种策略，参数策略和Accept策略，最终选择最优策略，参数策略优先）    可以以一个参数？format=xx   指定接受方式  xml或json   或自定义messageConverter的其他方式
server:
  servlet:
    #context-path: /world   #设置路由访问的前缀，加入之后，在thymeleaf中，会自动给渲染后的HTML模板加上前缀，非常方便
